name: super_image_selector
description: A lightweight and easy-to-use image selector package for Flutter (gallery, camera, multiple).
version: 1.0.0
homepage: https://github.com/prometteurShubhamK/super_image_selector
repository: https://github.com/prometteurShubhamK/super_image_selector
issue_tracker: https://github.com/prometteurShubhamK/super_image_selector/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  super_image_selector:
    path: ../    # This points to the plugin folder   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.example.super_image_selector
        pluginClass: SuperImageSelectorPlugin
      ios:
        pluginClass: SuperImageSelectorPlugin
